name: test
on: push
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          install: npm install
          start: npm run dev
          wait-on: 'npx --yes wait-on --timeout 60000 tcp:5173'
          spec: cypress/e2e/spec.cy.ts
      - name: Jest/RTL
        uses: actions/setup-node@v2
        with:
          start: npm test
